[package]
name = "hello_rust"
version = "0.1.0"
authors = ["maocq <mauriciocarmona@seven4n.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
